# Generated by Django 2.2 on 2020-09-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp25app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessdetails',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp25app.WebPage'),
        ),
    ]
